disabled_rules:
  - todo
  - statement_position
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - nesting

identifier_name:
  excluded:
    - id

line_length:
  ignores_comments: true

type_body_length:
  - 500
  - 800

file_length:
  warning: 800
  error: 1200
